## 演示0102：数组维度

### 案例1：数组维度和长度

> ** 与数组维度和大小有关的函数和属性**
* *len*函数总是返回数组第一个维度的大小
* *shape*属性返回数组每个维度的大小，使用一个*tuple*来代表；对于一维数组，*shape*属性仅记录了一个维度大小
* *size*属性用于记录元素总个数
* *itemsize*属性记录了每个元素所占字节数

In [1]:
import numpy as np
a1 = np.arange(10)
print(len(a1), a1.shape, a1.size, a1.itemsize)
a2 = np.array([[1,2,3,4],[5,6,7,8]], dtype=np.int64)
print(len(a2), a2.shape, a2.size, a2.itemsize)

10 (10,) 10 4
2 (2, 4) 8 8


### 案例2：访问数组中的元素

> ** 使用正数下标索引访问一维数组中的元素 **  
数组元素：[0 10 20 30 40 50 60 70 80 90]  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
$\downarrow$ &nbsp; $\downarrow$ &nbsp;$\downarrow$ &nbsp; $\downarrow$ &nbsp;$\downarrow$ &nbsp; $\downarrow$ &nbsp;$\downarrow$ &nbsp; $\downarrow$ &nbsp;$\downarrow$ &nbsp; $\downarrow$  
下标索引： 0 &nbsp; 1 &nbsp; 2 &nbsp; 3 &nbsp; 4 &nbsp; 5 &nbsp; 6 &nbsp; 7 &nbsp; 8 &nbsp; 9 &nbsp;  
* 下标索引从$0$开始编号
* 使用*[start:end:step]*的形式从数组中取出部分元素(切片)：从下标为*start*的元素开始，到下标为*end-1*的元素结束，每次移动*step*个元素
* 如果不明确指定*start*,*end*和*step*，则$start=0$, $end=len(a)$, $step=1$  

In [2]:
a1 = np.arange(10)*10
print(a1)
print(a1[0:len(a1)])    # start=0，end=10。从下标为0的元素开始，到下标为9(end-1=9)的元素结束
print(a1[0:])    # start=0，end=10
print(a1[:])     # start=0, end=10
print(a1[1:])    # start=1, end=10
print(a1[1:len(a1):2])    # start=1, end=10, step=2
print(a1[1::2])    # start=1, end=10, step=2
print(a1[::2])    # start=0, end=10, step=2

[ 0 10 20 30 40 50 60 70 80 90]
[ 0 10 20 30 40 50 60 70 80 90]
[ 0 10 20 30 40 50 60 70 80 90]
[ 0 10 20 30 40 50 60 70 80 90]
[10 20 30 40 50 60 70 80 90]
[10 30 50 70 90]
[10 30 50 70 90]
[ 0 20 40 60 80]


> ** 使用负数下标索引访问一维数组中的元素 **  
数组元素：[&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;10&nbsp;&nbsp;&nbsp;20&nbsp;&nbsp;30&nbsp;&nbsp;40&nbsp;&nbsp;50&nbsp;&nbsp;60&nbsp;&nbsp;70&nbsp;&nbsp;80&nbsp;&nbsp;90]  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
$\downarrow$ &nbsp;&nbsp; $\downarrow$ &nbsp;&nbsp;&nbsp;$\downarrow$ &nbsp;&nbsp; $\downarrow$ &nbsp;&nbsp;$\downarrow$ &nbsp;&nbsp; $\downarrow$ &nbsp;&nbsp;$\downarrow$ &nbsp;&nbsp; $\downarrow$ &nbsp;&nbsp;&nbsp;$\downarrow$ &nbsp;&nbsp; $\downarrow$  
下标索引： -10&nbsp;&nbsp; -9&nbsp;&nbsp; -8&nbsp;&nbsp; -7&nbsp;&nbsp; -6&nbsp;&nbsp; -5&nbsp;&nbsp; -4&nbsp;&nbsp; -3&nbsp;&nbsp; -2&nbsp;&nbsp; -1 
* 最后一个元素的下标索引为$-1$,依次向前(左)减少 
* 使用*[start:end:step]*形式取出数组中的某个部分(切片)时。默认情况下，$step=1$
* 当$step\gt0$，默认$start=-(len(a))$， $end=0$, 从下标为*start*的元素开始取，到下标为*end-1*的元素结束
* 当$step\lt0$(例如$step=-1$)，则默认$start=-1$, $end=-(len(a)+1)$。从下标为*start*的元素开始，向前(左)步进(每次*step*步)，一直到下标为*end+1*的元素结束

In [3]:
a1 = np.arange(10)*10
print(a1)
print(a1[-1])    # 下标为-1的元素(最后一个元素)
print(a1[:-1])    # start=-len(a), end=-1。从第一个元素开始，到下标为-2(end-1=-2)的元素结束
print(a1[-4:])    # start=-4，end=0。从下标为-4的元素开始，到下标为-1(end-1=-1)的元素结束
print(a1[-4:-1])    # start=-4，end=-1。从下标为-4的元素开始，到下标为-2(end-1=-2)的元素结束
print(a1[6:2:-1])    # start=6, end=2, step=-1。从正下标为6的元素开始，到正下标为3(end+1=3)的元素结束，向前(左)依次取元素
print(a1[-2:2:-1])    # start=-2, end=2, step=-1。从负下标为-2的元素开始，到正下标为3(end+1=3)的元素结束，向前(左)依次取元素
print(a1[::-1])    # start=-1，end=-(10+1)=-11。从负下标为-1元素开始，到负下标为-10(end+1=-10)的元素结束，向前(左)依次取元素

[ 0 10 20 30 40 50 60 70 80 90]
90
[ 0 10 20 30 40 50 60 70 80]
[60 70 80 90]
[60 70 80]
[60 50 40 30]
[80 70 60 50 40 30]
[90 80 70 60 50 40 30 20 10  0]


> **使用下标索引访问二维数组/矩阵中的单个元素**  
* 分为*row*和*col*两个维度索引，分别表示行下标和列下标。行、列的下标均从$0$开始。
* *[row][col]*或*[row, col]*形式的效果相同

In [4]:
a= np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(a[1,2])    # 行下标为1，列下标为1的元素
print(a[1][2])

8
8


> **访问二维数组/矩阵中的部分数据(切片)**  
* 行、列下标可以采用与一维数组类似的方式进行处理
* 如果最终的切片结果只有一行或一列，则该结果将被转成一个一维数组

In [5]:
a= np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(a[0:2,2:5])    # 行下标0，1行，列下标2,3,4列
print(a[:, 2:5])    # 行下标所有行，列下标2,3,4列
print(a[:,3])    # 行下标所有行，列下标为3的列。注意，因为最终只返回了1列，因此该列数据被转换成一维数组
print(a[1,:])    # 行下标为1的行，列下标所有列。注意，因为最终只返回了1行，因此改行数据被转换成一维数组
print(a[1])    # 如果省略了列维度，则默认取所有列

[[ 3  4  5]
 [ 8  9 10]]
[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]
[ 4  9 14]
[ 6  7  8  9 10]
[ 6  7  8  9 10]


> **通过*[start:end:step]*方式得到的切片数据，与原数组共享内存地址**

In [6]:
a = np.array([1,2,3,4,5])
b = a[0:2]
b[0] = 100
print(a)    # a的第一个元素被修改为100

[100   2   3   4   5]


### 案例3：变更数组的维度

> ** 将维度为(3,4)的数组转变成(4,3)数组形式**  
* *reshape*方法：
 * 必须保证变形前后的总元素个数相同
 * 变形前后不会产生新的拷贝数据。即：变形前后两个变量共享同一块数据内存
 * 虽然两个变量共享相同的数据内存，但是它们各自维护自己的维度
* *np.resize*方法：
 * 变形后的总元素个数可以不同于变形前的
 * *np.resize(a,(M, N))*，不会修改a的维度，将返回一个$(M, N)$的数组拷贝
 * *np.resize(a, (M,N))*与*a.resize((M,N))*的行为并不相同，本实验不作演示

In [7]:
a1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a2 = a1.reshape((4, 3))
# a2 = np.reshape(a1, (4, 3))    # 与上一行相同效果
print(a2)
a1[0, 0] = 100
print(a2[0, 0])    # 与a1共享数据内存
print("a1.shape=", a1.shape)
print("a2.shape=", a2.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
100
a1.shape= (3, 4)
a2.shape= (4, 3)


In [8]:
a1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a2 = np.resize(a1, (4, 3))
print(a2)
a1[0, 0] = 100
print(a2[0, 0])    # 各自拥有独立的数据内存

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
1


In [9]:
a1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a2 = np.resize(a1, (2, 3))    # 仅取前6个元素转成2x3数组
print(a2)
a3 = np.resize(a1, (5, 3))    # 变形后的元素个数更多，这时将反复填充原始数组中的数据
print(a3)

[[1 2 3]
 [4 5 6]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [ 1  2  3]]


> **行向量与列向量**  
* 形如[1 2 3 4 5]的向量，称作**行向量**
 * 行向量实际上可视为一维数组
 * 可通过：<code>np.array([1,2,3,4,5])</code>定义
 * *shape*表示为(5, )
 * 一般不把形如 [[1 2 3 4 5]]的$(1, N)$维度矩阵视为行向量，虽然它代表了矩阵中的一行。shape表示为(1, 5)
* 形如$ \left[\begin{matrix}1 \\ 2 \\ 3 \\ 4 \\ 5\end{matrix}\right] $的向量，称作**列向量**
 * 列向量实际上是一个$(N, 1)$维度的矩阵
 * 可通过：<code>np.array([[1],[2],[3],[4],[5]])</code>定义
 * *shape*表示为(5, 1)
* 行向量转成列向量
 * *newaxis*操作符。操作前后两个变量引用同一块数据内存，但是维护各自的shape信息
 * *reshape*。可以使用-1让函数自动推算某个维度的长度
 * *resize*。需要明确指出维度长度，不能通过-1让函数自动推算
* 列向量转成(1,N)维度矩阵
 * *reshape*或*resize*
* 列向量转成(N，)维度的行向量(一维数组)
 * *ravel*：转换前后共享数据内存
 * *flatten*：转换后拷贝一份内存。注意应通过对象来调用*flatten*，而不能使用*np.flatten*
 * $(M,N)$维度的二维数组/矩阵，同样可以通过*ravel*或*flatten*展成一维数组

In [10]:
# 行向量转列向量
a = np.array([1,2,3,4,5])
b = a[:, np.newaxis]
c = np.reshape(a, (-1, 1))    # -1表示行数维度由函数自行推算
d = np.resize(a, (len(a), 1))
print(b)
print(c)
print(d)

[[1]
 [2]
 [3]
 [4]
 [5]]
[[1]
 [2]
 [3]
 [4]
 [5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


In [11]:
# 列向量转(1,N)维度矩阵
a = np.array([[1],[2],[3],[4],[5]])
b = a.reshape((1, -1))
print(b)

[[1 2 3 4 5]]


In [12]:
# 列向量转(N,)行向量(一维数组)
a = np.array([[1],[2],[3],[4],[5]])
b = np.ravel(a)
c = a.flatten()
print(b)
print(c)

[1 2 3 4 5]
[1 2 3 4 5]
