## 演示0104：数组元素查找与统计

### 案例1：数组极值

> **一维数组极值 **
* *np.max*和*np.min*用于查找最大值和最小值
* *np.argmax*和*np.argmax*用于查找极值元素对应的下标索引

In [1]:
import numpy as np

a = np.array([3, 1, 7, 4, 2, 5, 8])
print("最大元素下标：", np.argmax(a), "最大值：", np.max(a))
print("最小元素下标：", np.argmin(a), "最小值：", np.min(a))

最大元素下标： 6 最大值： 8
最小元素下标： 1 最小值： 1


> **二维数组极值**  
* 设置*axis=0*，表示沿着竖直方向(行索引增长的方向)，为每一列分别查找极值(一维数组，长度为原二维数组列数)
* 设置*axis=1*，表示沿着水平方向(列索引增长的方向)，为每一行分别查找极值(一维数组，长度为原二维数组行数)
* 不设置*axis*时，将查找整个数组中的极值元素(单个值，标量)

In [2]:
a = np.array([[1,2,3],[4,5,6]])
b = np.max(a)
c = np.max(a, axis=0)
d = np.max(a, axis=1)
print(b)
print(c)
print(d)

6
[4 5 6]
[3 6]


> **二维数组极值对应的元素索引**
* *argmax*和*argmin*返回极值对应的索引
* 如果没有指定*axis*，则返回极值元素在整个二维数组中的索引号(将二维数组展成一维数组)
* *axis=0*时，分别返回每个列的极值在该列中的索引号
* *axis=1*时，分别返回每个行的极值在该行中的索引号

In [3]:
a = np.array([[1,2,3],[4,5,6]])
b = np.argmax(a)
c = np.argmax(a, axis=0)
d = np.argmax(a, axis=1)
print(b)
print(c)
print(d)

5
[1 1 1]
[2 2]


### 案例2：求和、平均值

> **算数平均值与加权平均值**  
* *np.mean*用于计算算数平均值
* *np.average*计算加权平均值。需要给定一个权重数组(数组中每个权重对应着待统计数组中的每个元素值)
* 可以这样理解加权计算：将权重数组中的每个元素值换算成占总权重数的百分比，然后与待统计数组中对应的元素做乘积，最后求和

In [4]:
a = np.arange(1, 11)
print(np.mean(a))
weights1 = np.ones(10)
print(np.average(a, weights=weights1))    # 权重数组中每个竖直都为1，可视为每个权重都是0.1
weights2 = [1,0,1,0,1,0,1,0,1,0]    # 权重换算成百分比后为：[0.2，0，0.2，0，0.2，0，0.2，0，0.2，0]
print(np.average(a, weights=weights2))

5.5
5.5
5.0


In [5]:
# 自定义的加权平均计算方法
def my_average(arr, weights):
    weights = weights / np.sum(weights)
    average = 0.0
    for i in range(len(arr)):
        average += arr[i] * weights[i]
    return average

print(my_average(a, weights1))
print(my_average(a, weights2))

5.500000000000001
5.0


> **二维数组的和与均值计算**  
* 不设置*axis*时，计算整个二维数组的和/均值
* *axis=0*时，沿竖直方向(行索引增长的方向)，计算每个列的和/均值
* *axis=1*时，沿水平方向(列索引增长的方向)，计算每个行的和/均值

In [6]:
a = np.array([[1,2,3],[4,5,6]])
print(np.sum(a), np.mean(a))
print(np.sum(a, axis=0), np.mean(a, axis=0))
print(np.sum(a, axis=1), np.mean(a, axis=1))

21 3.5
[5 7 9] [2.5 3.5 4.5]
[ 6 15] [2. 5.]


### 案例3：统计非零元素个数

> **统计一维和二维数组中的非零元素个数**
* *np.count_nonzero*
* 通过设置*axis*参数，可以计算每列或每行的非零元素个数

In [7]:
a= np.array([[1,2,0,0],[1,0,0,1],[0,0,1,1]])
print(np.count_nonzero(a))
print(np.count_nonzero(a,axis=0))
print(np.count_nonzero(a,axis=1))

6
[2 1 1 2]
[2 2 2]
