## 演示0105：数组排序

### 案例1：一维数组排序

> **升序和降序排列**  
* *sort*只能升序排列，如果需要降序，可以再倒序

In [1]:
import numpy as np

a = np.array([3, 1, 7, 4, 2, 5, 8])
b = np.sort(a)
print(b)
print(b[::-1])    # 使用[::-1]进行倒序遍历

[1 2 3 4 5 7 8]
[8 7 5 4 3 2 1]


> ** *np.sort(a)*和*a.sort*的不同行为 **  
* *np.sort(a)*不修改a的值，而是返回一个拷贝，该拷贝是排序后的
* *a.sort()*返回None，它将直接在a上进行排序

In [2]:
a = np.array([3, 1, 7, 4, 2, 5, 8])
b = np.sort(a)
print(a)
a.sort()
print(a)

[3 1 7 4 2 5 8]
[1 2 3 4 5 7 8]


### 案例2：二维数组排序

>** 按行或案列排序**  
* 指定*axis=0*，表示沿竖直方向(行索引增加的方向)，对每一列分别排序
* 指定*axis=1*，表示沿水平方向(列索引增加的方向)，对每一行分别排序
* 未指定*axis*时，行为等同于*axis=1*

In [3]:
a = np.array([[1,4,3],[3,1,8], [2,0,7]])
print(np.sort(a))
print(np.sort(a, axis=0))
print(np.sort(a, axis=1))

[[1 3 4]
 [1 3 8]
 [0 2 7]]
[[1 0 3]
 [2 1 7]
 [3 4 8]]
[[1 3 4]
 [1 3 8]
 [0 2 7]]


### 案例3：数据分区

>** 根据某个边界数，将数组中的数据分成两个区，左区的值均小于边界数，右区的值均大于边界数**  
* $np.partition$函数用于执行分区操作。该函数指定边界元素的下标索引号，分区完成后，该下标索引号左边的元素值都小于该边界元素，右边的元素都大于该边界元素
* 左区和右区内部的数据并不会进行排序

In [4]:
a = np.array([30, 80, 70, 100, 50, 40, 20, 90])
b = np.partition(a, 0)    # 分区完成后，0号索引位置右边的元素都大于该位置元素值
c = np.partition(a, 6)    # 分区完成后，6号索引位置左边的元素都小于该位置元素值；右边的元素都大于该位置元素值
print(b)    # 0号索引位置元素值为20
print(c)    # 6号索引位置元素值为90

[ 20  80  70 100  50  40  30  90]
[ 20  30  70  80  50  40  90 100]
