## 演示0107：数组拼接与拆分

### 案例1：拼接数组

> **将数组：** $ \left[\begin{matrix}1 & 2 & 3 \\4 & 5 & 6 \\ \end{matrix}\right] $ **和** $ \left[\begin{matrix}7 & 8 & 9 \\10 & 11 & 12 \\ \end{matrix}\right] $ **组合成：**$ \left[\begin{matrix}1 & 2 & 3 \\4 & 5 & 6 \\7 & 8 & 9 \\10 & 11 & 1\\ \end{matrix}\right] $  
* *np.concatenate*函数，通过指定*axis=0*，将两个数组沿竖直方向(行索引增长的方向)组合拼接
* *np.vstack*函数。按照竖直(vertical)方向拼接
* 将要拼接的数组放在一个*tuple*中，并且这些数组应具有相同的列数
* 支持多个数组的拼接
* 拼接后的数组与原来的数组不共享数据内存

In [1]:
import numpy as np

a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([[7,8,9],[10,11,12]])
b1 = np.concatenate((a1, a2), axis=0)    # axis=0可以省略
b2 = np.vstack((a1, a2))
print(b1)
print(b2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [2]:
# 支持多个同shape数组的拼接
a3 = np.array([[13,14,15],[16,17,18]])
b3 = np.vstack((a1, a2, a3))
print(b3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


> **将数组：** $ \left[\begin{matrix}1 & 2 & 3 \\4 & 5 & 6 \\ \end{matrix}\right] $ **和** $ \left[\begin{matrix}7 & 8 \\9 & 10 \\ \end{matrix}\right] $ **组合成：**$ \left[\begin{matrix}1 & 2 & 3 & 7 & 8 \\4 & 5 & 6 & 9 & 10 \end{matrix}\right] $  
* *np.concatenate*函数，通过指定*axis=1*，将两个数组沿水平方向(列索引增长的方向)组合拼接
* *np.hstack*函数。按照水平(horizontal)方向拼接
* 拼接的数组应具有相同的行数

In [3]:
a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([[7,8],[9,10]])
b1 = np.concatenate((a1, a2), axis=1)
b2 = np.hstack((a1, a2))
print(b1)
print(b2)

[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]
[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


### 案例2：数组拆分

> **二维数组/矩阵的水平或数值拆分**  
* *split*(指定*axis=0*)或*vsplit*均可用于在竖直方向上(沿着行索引增长的方向)将所有行进行拆分
* *split*(指定*axis=1*)或*hsplit*均可用于在水平方向上(沿着列索引增长的方向)将所有列进行拆分
* 在水平方向上拆分数组，拆分后的各个数组具有相同的列数。如果不能等分列数，则拆分失败
* 在竖直方向上拆分数组，拆分后的各个数组具有相同的行数。如果不能等分行数，则拆分失败
* 拆分后的各个数组，组成一个新的数组。此时将构成一个三维数组，其中每个元素是一个二维数组

In [4]:
a= np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
b= np.split(a, 2, axis=0)    # 在竖直方向上，将所有行拆成2等分，
c = np.vsplit(a, 2)
d = np.split(a, 5, axis=1)    # 在水平方向上，将所有行拆成5等分，
e = np.hsplit(a, 5)
print(b)
print(d)

[array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])]
[array([[ 1],
       [ 6],
       [11],
       [16]]), array([[ 2],
       [ 7],
       [12],
       [17]]), array([[ 3],
       [ 8],
       [13],
       [18]]), array([[ 4],
       [ 9],
       [14],
       [19]]), array([[ 5],
       [10],
       [15],
       [20]])]
