## 演示0201：数组运算

### 案例1：数组与标量的运算

>** 数组与标量运算，相当于数组中每个元素分别于该标量进行计算**  
* 建议尽量调用*numpy*中的函数。这些函数都支持以一维或多维数组作为参数；而*python*内建的运算函数有可能不支持数组

In [1]:
import numpy as np

a = np.array([1, 2, 4, 8, 16])
print(a)
print(a + 5)
print(a * 5)
print(a**2)    # 平方运算
print(pow(2, a))    # 2的a次幂
print(np.prod(a))    # 每个元素连乘
print(np.log2(a))    # 以2为底的对数

b = np.array([[1,2,4],[8,16,32]])
print(np.log2(b))

[ 1  2  4  8 16]
[ 6  7  9 13 21]
[ 5 10 20 40 80]
[  1   4  16  64 256]
[    2     4    16   256 65536]
1024
[0. 1. 2. 3. 4.]
[[0. 1. 2.]
 [3. 4. 5.]]


### 案例2：数组与数组的元素级运算

>**同维度数组之间的元素级运算**  
* 对应元素之间分别计算

In [2]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print(a+b)
print(a*b)

[ 7  9 11 13 15]
[ 6 14 24 36 50]


In [3]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
print(a+b)
print(a*b)

[[ 8 10 12]
 [14 16 18]]
[[ 7 16 27]
 [40 55 72]]


>** 二维数组与一维数组之间的元素级运算**  
* 设*a*为$(M,N)$二维数组
 * 若*b*为$(N,)$一维数组或$(1,N)$二维数组，则$a+b$成立($b+a$相同)。相当于*a*中的每一行，分别与b进行元素级操作
 * 若*b*为$(K,)$一维数组($K \neq N$)，则$a+b$不成立。因为*a*中的每一行，无法与*b*进行元素级操作
 * 若*b*为$(N,1)$二维数组(列向量)，则$a+b$成立($b+a$相同)。相当于a中的每一列，分别与*b*进行元素级操作
 * 若*b*为$(K,1)$二维数组($K \neq N$)，则$a+b$不成立。因为*a*中的每一列，无法与*b*进行元素级操作

In [4]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
b = np.array([10,20,30,40,50])
c = np.array([[10],[20],[30]])
print(a+b)
print(a+c)

e =np.array([10,20,30])
# a+e    # 错误，每行元素数量不同
f = np.array([[10],[20]])
# a+f    # 错误，每列元素数量不同

[[11 22 33 44 55]
 [16 27 38 49 60]
 [21 32 43 54 65]]
[[11 12 13 14 15]
 [26 27 28 29 30]
 [41 42 43 44 45]]


### 案例3：$*$操作符

>** $*$操作符始终进行元素级的乘法运算**  
* $a*b$与$b*a$具有相同的效果

In [5]:
# 二维数组与一维数组运算
A = np.array([[1,2,3],[4,5,6]])
a = np.array([1,2,3])
b = np.array([[1],[2]])
c = np.array([[1],[2],[3]])
print(A*a)    # 正确，A中每一行分别与a进行元素级乘法运算。二者元素个数相同
print(A*b)    # 正确，A中的每一行与b对应行进行元素级乘法运算。b中每行只有1个元素，相当于标量计算
#print(A*c)    # 错误，A只有2行，但c有3行，因此c中最后一行数据找不到A中对应的数据进行计算

B = np.array([[1,2],[3,4],[5,6]])
#print(B*a)    # 错误，B每行只有2个元素，无法与a(每行3个元素)进行元素级运算
#print(B*b)    # 错误，B有3行，但b只有2行，因此B的最后一行找不到对应的数据进行计算
print(B*c)    # 正确，B中的每一行分别于c对应的每一行进行元素级乘法运算。c中每行只有1个元素，相当于标量计算

[[ 1  4  9]
 [ 4 10 18]]
[[ 1  2  3]
 [ 8 10 12]]
[[ 1  2]
 [ 6  8]
 [15 18]]


In [6]:
# 一维数组之间的运算
a = np.array([1,2,3])
b = np.array([[1],[2]])
c = np.array([1,2])
d = np.array([[1,2],[3,4]])
print(a*b)    # 正确，将a与b中每行分别进行元素级乘法运算。b中每行只有1个元素，相当于标量计算
#print(a*c)    # 错误,a和c都是一维数组，但元素个数不同，无法进行元素级计算
#print(a*d)    # 错误,a无法与d中的某一行进行元素级计算，因为它们元素个数不同

[[1 2 3]
 [2 4 6]]


>**行向量与列向量的$*$操作**  
* 维度为$(N,)$的一维数组(行向量)*a*与维度为$(M,1)$的列向量*b*进行元素级运算，得到$(N,M)$二维数组
* 相当于用*a*与*b*的每行(仅有1个元素)进行元素级乘法

In [7]:
a = np.array([1,2,3,4,5])    #(5)
b = np.array([[1],[2],[3]])    # (3, 1)
print(a*b)    # (5,3)

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]]
