## 演示0202：矩阵与向量运算

### 案例1：数组内积和

>** 两个一维数组的内积和**  
* 对应元素相乘然后再求和
* 向量的维度(元素个数)必须相同
* *np.dot(a, b)*或者*a.dot(b)*均可以计算内积和

In [2]:
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([2,4,6,8,10])
print(a.dot(b))
print(np.dot(a, b))

110
110


>**二维数组(矩阵)*A*与列向量*a*的乘积**  
* 将*a*视为一个一维数组，将矩阵*A*的第一行与*a*进行内积和操作，结果作为第一行(只有1个元素)
* *A*的第二行与*a*内积和，结果作为第二行(同样只有1个元素)
* 依次类推，维度为*(N,M)*的矩阵*A*与a乘积后，将生成一个具有*N*行的数组(每行只有1个元素),也即*(N,1)*列向量
* 要求*A*的列数*M*必须与*a*的长度相同

In [4]:
A = np.array([[1,2,3,4,5], [6,7,8,9,10],[11,12,13,14,15]])    # (3,5)矩阵
a = np.array([[1],[2],[3],[4],[5]])    # (5,1)列向量
print(A.dot(a))    # (3,1)列向量

[[ 55]
 [130]
 [205]]


>**二维数组(矩阵)*A*与一维数组*a*的内积和运算**  
* *A*的每一行(一维数组)，分别与*a*做内积和；各次操作结果形成一个一维数组
* 要求*A*的列数必须与*a*的长度相同，否则无法进行内积运算
* 使用*A.dot(a)*或*np.dot(A, a)*均可
* 注意，此时的*a*仅是一位数组(不是列向量)，其结果也有所不同

In [5]:
A = np.array([[1,2,3,4,5], [6,7,8,9,10],[11,12,13,14,15]])
a = np.array([10,20,30,40,50])
print(A.dot(a))    # 维度为(3,)的一维数组

[ 550 1300 2050]


### 案例2：矩阵乘法

>** *(M,N)*维度矩阵*A*和*(N,K)*维度矩阵*B*相乘**  
* *A*的列数必须与*B*的行数相同
* 可理解为：
 * *A*的第1行与*B*的第1列进行内积和，结果作为第1行第1个元素
 * *A*的第1行与*B*的第2列进行内积和，结果作为第1行第2个元素
 * 依次类推，第1行一共产生了*K*个内积和
 * *A*的第2行与*B*的每一列分别执行上述操作，再次产生*K*个内积和
 * 直到*A*的最后一行与*B*的每一列计算完毕
 * 最终产生*(M,K)*结果矩阵
* *A.dot(B)*与*B.dot(A)*的含义是完全不同的

In [6]:
A = np.array([[1,2,3,4,5], [6,7,8,9,10],[11,12,13,14,15]])    # (3,5)
B = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4],[5,5,5,5]])    #(5,4)
C = np.dot(A, B)    #(3,4)
print(C)

[[ 55  55  55  55]
 [130 130 130 130]
 [205 205 205 205]]


>**特殊维度的矩阵相乘**  
* *(M,1)*矩阵与*(1,K)*矩阵相乘，得到*(M,K)*矩阵
* *(1,N)*矩阵与*(N,K)*矩阵相乘，得到*(1,K)*矩阵
* *(1,N)*矩阵与*(N,1)*矩阵相乘，得到*(1,1)*矩阵

In [9]:
A1 = np.array([[1],[2],[3],[4],[5]])  # (5,1)
A2 = np.array([[1,2,3,4,5]])    # (1,5)
A3 = np.array([[1,1,1],[2,2,2],[3,3,3],[4,4,4],[5,5,5]])   #(5,3)
print(A1.dot(A2))    # (5, 5)
print(A2.dot(A1))    # (1,1)。注意这个结果并不是一个标量，而是具有1行1列的二维数组(矩阵)
print(A2.dot(A3))    # (1, 3)

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]
[[55]]
[[55 55 55]]


### 案例3：一维数组与矩阵的乘积

>**维度为*(N,)*的一维数组*a*与二维数组*A*的乘积**  
* *a*与*A*中的每一列进行内积和，将所有结果放在一个一维数组中
* 要求*A*必须具有*N*行

In [10]:
a = np.array([1,2,3,4,5])    # (5,)
b = np.array([[1,1,1],[2,2,2],[3,3,3],[4,4,4],[5,5,5]])    # (5,3)
print(a.dot(b))    # (3,)一维数组

[55 55 55]
